export const AUTH_LOADING = "AUTH_LOADING";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";

export const USER_LOADING = "USER_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const SNIPPET_EXEC_LOADING = "SNIPPET_EXEC_LOADING";
export const SNIPPET_EXEC_SUCCESS = "SNIPPET_EXEC_SUCCESS";
export const SNIPPET_EXEC_FAILED = "SNIPPET_EXEC_FAILED";

export const LANGUAGES_LOADING = "LANGUAGES_LOADING";
export const LANGUAGES_LOADED = "LANGUAGES_LOADED";

//current Snippet
export const SET_SNIPPET_BODY = "SET_SNIPPET_BODY";
export const SET_SNIPPET_LANGUAGE = "SET_SNIPPET_LANGUAGE";
export const SET_SNIPPET_TITLE = "SET_SNIPPET_TITLE";
export const SET_SNIPPET_VISIBILITY = "SET_SNIPPET_VISIBILITY";
export const SET_SNIPPET_DESCRIPTION = "SET_SNIPPET_DESCRIPTION";
export const SET_SNIPPET_LANGUAGE_VERSION = "SET_SNIPPET_LANGUAGE_VERSION";
export const SET_SNIPPET_SLUG = "SET_SNIPPET_SLUG";

export const SET_SNIPPET_EDIT_MODE = "SET_SNIPPET_EDIT_MODE";
export const SNIPPET_EDIT_LOADING = "SNIPPET_EDIT_LOADING";
export const SNIPPET_EDIT_SUCCESS = "SNIPPET_EDIT_SUCCESS";

export const SNIPPET_SAVE_LOADING = "SNIPPET_SAVE_LOADING";
export const SNIPPET_SAVE_SUCCESS = "SNIPPET_SAVE_SUCCESS";
export const RESET_CURRENT_SNIPPET = "RESET_CURRENT_SNIPPET";
